name: Build with CPack

on:
  push:
    branches:
      - build-cmake
    paths-ignore:
      - '**.md'

defaults:
  run:
    shell: bash

jobs:
  job:
    name: ${{ matrix.os }}-${{ github.workflow }}-test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-latest ]
        include:
          - os: windows-latest
            triplet: x64-windows
            vcpkg_installation_root: C:/vcpkg
    #            - os: ubuntu-latest
    #              triplet: x64-linux
    #            - os: macos-latest
    #              triplet: x64-osx

    env:
      VCPKG_DEFAULT_TRIPLET: ${{ matrix.triplet }}
      VCPKG_ROOT: ${{ matrix.vcpkg_installation_root }}

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          token: ${{ secrets.GH_PAT }}
      - name: update vcpkg
        run: $VCPKG_ROOT/bootstrap-vcpkg.sh
      - name: Build
        run: |
          mkdir build
          cd build
          cmake \
            -DGFP_WITH_LOD2=OFF \
            -DVCPKG_DEFAULT_TRIPLET=$VCPKG_DEFAULT_TRIPLET \
            -DCMAKE_TOOLCHAIN_FILE=$VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake \
            ..
          cmake --build . --config Release
          cpack -C Release --verbose