name: Build with CPack

on:
  push:
    branches:
      - build-cmake
    paths-ignore:
      - '**.md'

defaults:
  run:
    shell: bash

jobs:
  job:
    name: ${{ matrix.os }}-${{ github.workflow }}-test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-latest ]
        include:
          - os: windows-latest
            triplet: x64-windows
            vcpkg_installation_root: C:/vcpkg
            exe_ext: exe
            exe_os: win64
    #            - os: ubuntu-latest
    #              triplet: x64-linux
    #            - os: macos-latest
    #              triplet: x64-osx

    steps:
      - name: get vcpkg version
        run: echo "VCPKG_VERSION=$(vcpkg version | grep -o '[0-9].*')" >> $GITHUB_ENV
      - name: print vcpkg version
        run: echo $VCPKG_VERSION
      - name: print vcpkg version
        run: echo ${{ env.VCPKG_VERSION }}
